"""initial_schema

Revision ID: 5b2e14cfb7a1
Revises: 
Create Date: 2026-07-12 00:09:05.489586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b2e14cfb7a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_logs', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'expense_items', 'receipts', ['receipt_id'], ['id'])
    op.add_column('expenses', sa.Column('merchant_name', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'notes')
    op.drop_column('expenses', 'merchant_name')
    op.drop_constraint(None, 'expense_items', type_='foreignkey')
    op.alter_column('ai_logs', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
