"""Describe your next change

Revision ID: c72ca0db04b5
Revises: 5221f94f9292
Create Date: 2026-06-30 18:36:17.947069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c72ca0db04b5'
down_revision: Union[str, Sequence[str], None] = '5221f94f9292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_logs', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('expense_items', 'receipt_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('expense_items_ibfk_2'), 'expense_items', type_='foreignkey')
    op.drop_column('expense_items', 'expense_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_items', sa.Column('expense_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('expense_items_ibfk_2'), 'expense_items', 'expenses', ['expense_id'], ['id'])
    op.alter_column('expense_items', 'receipt_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ai_logs', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
